version: "3"
services: 
  mysql_knex:
    env_file:
    - .env
    container_name: mysql_knex
    hostname: mysql_knex
    image: mysql:8.0
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes: 
      - "C:\\Users\\PC\\OneDrive\\teste\\trabalho\\docker_recebe:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      TZ: America/Sao_Paulo